proxy:
 service:
   type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 256M
  hosts:
    - dive.cs.cityu.edu.hk
  pathType: Prefix 

hub:
  baseUrl: /cs1302_23a
  nodeSelector:
    kubernetes.io/hostname: dive
  image:
    name: localhost:32000/hub
    tag: 0.0.2a
  config:
    Authenticator:
      admin_users:
        - ccha23
        - ruoqitang2
    JupyterHub:
      admin_access: true
  extraConfig:
    01-radius-auth: |
      import subprocess
      from shlex import quote
      from jupyterhub.auth import PAMAuthenticator

      class MyAuthenticator(PAMAuthenticator):

        def system_user_exists(self, user):
          cmd = 'getent passwd {}'.format(quote(user.name))
          try:
            subprocess.check_output(cmd, shell=True).decode("utf-8").strip()
          except subprocess.CalledProcessError as e:
            return False
          else:
            return True

      c.JupyterHub.authenticator_class = MyAuthenticator
    02-collab-group: |
      c.JupyterHub.load_groups = {
          # collaborative accounts get added to this group
          # so it's easy to see which accounts are collaboration accounts
          "collaborative": [
            "grader-cs1302",
            "all-cs1302"
          ],
          "grader": [
            "grader-cs1302",
          ],
          "formgrade-cs1302": []
      }

      c.JupyterHub.load_roles = [
        {
          "name": "access-grader-cs1302",
          "scopes": [
              "access:servers!user=grader-cs1302",
              "admin:servers!user=grader-cs1302",
              "admin-ui",
              "list:users!user=grader-cs1302",
              "access:servers!user=all-cs1302",
              "admin:servers!user=all-cs1302",
              "list:users!user=all-cs1302",              
          ],
          "groups": ["formgrade-cs1302"],
        },
        {
          "name": "user",
          "scopes": [
              "self",
              "servers!user=all-cs1302",
          ],
        }        
      ]

      def pre_spawn_hook(spawner):
        group_names = {group.name for group in spawner.user.groups}

        if "grader" in group_names:
          spawner.log.info(f"Changing UID for {spawner.user.name}")
          spawner.uid = 2000
          spawner.gid = 100

        exchange = {
          'name': 'volume-grader-2dcs1302',
          'persistentVolumeClaim': {
            'claimName': 'claim-grader-2dcs1302'
          },
          'mountPath': '/opt/conda/srv/exchange',
          'subPath': 'exchange',
          'home': '/home/nbgrader'
        }

        if spawner.user.name != "grader-cs1302":
          spawner.volumes.extend([
            {
              'name': exchange['name'],
              'persistentVolumeClaim': exchange['persistentVolumeClaim']
            }         
          ])
        else:
          # spawner.environment['NB_USER'] = 'nbgrader'
          # spawner.notebook_dir = '/home/nbgrader'
          spawner.volume_mounts.extend([
            {
              'name': exchange['name'],
              'mountPath': exchange['home']
            }        
          ])
        spawner.volume_mounts.extend([
          {
            'name': exchange['name'],
            'mountPath': exchange['mountPath'],
            'subPath': exchange['subPath']
          }        
        ])

      c.Spawner.pre_spawn_hook = pre_spawn_hook

    03-custom-profile-list: |
      # https://github.com/jupyterhub/jupyterhub/issues/2390

      from kubespawner import KubeSpawner

      class MyKubeSpawner(KubeSpawner):
        async def options_form(self, spawner):
          group_names = {group.name for group in spawner.user.groups}

          if "collaborative" in group_names:
            spawner.log.info(f"Enabling RTC for user {spawner.user.name}")

            spawner.profile_list.extend(
              [
                  {
                      'display_name': 'Collaborative',
                      'description': 'Jupyter server with jupyterlab-collaboration.',
                      'kubespawner_override': {
                          'image': 'localhost:32000/cs1302nb__collab:0.1.2a',
                      },
                      'default': True,                      
                  },
              ]
            )
          return spawner._options_form_default()

      c.JupyterHub.spawner_class = MyKubeSpawner



cull:
  enabled: true
  users: false
  adminUsers: false
  removeNamedServers: false
  timeout: 300
  every: 60
  concurrency: 60
  maxAge: 600

debug:
  enabled: true

singleuser:
  cmd: start-singleuser.sh
  image: 
    name: localhost:32000/cs1302nb
    tag: 0.1.1c
  storage:
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      pvcNameTemplate: claim-{username}
      volumeNameTemplate: volume-{username}      
      storageClass: home-dive0-nfs
  memory:
    limit: 8G
    guarantee: 1G
  cpu:
    limit: 4
    guarantee: 0.25
  networkPolicy:
    egressAllowRules:
      privateIPs: true
  extraNodeAffinity:
    preferred:
    - weight: 1
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dkw1
          - dkw2
  profileList:
    - default: true
      display_name: Default
      description: |
        Default jupyter server run on Ubuntu.
      kubespawner_override:
        image: localhost:32000/cs1302nb:0.1.2a
    - display_name: Alpine
      description: |
        Lightweight jupyter server run on Alpine Linux. It may run faster but has less features.
      kubespawner_override:
        image: localhost:32000/cs1302nb_alpine:0.1.2a     
    - display_name: bugbook
      description: |
        *** UNDER DEVELOPMENT ***
      kubespawner_override:
        image: localhost:32000/cs5489-notebook:0.0.2a

