#!/bin/bash

jupyter server extension enable --user nbgrader.server_extensions.formgrader
jupyter server extension enable --user nbgrader.server_extensions.course_list

# Disable first to create an entry in .jupyter/labconfig/page_config.json so that 
# labextensions can be enabled later to override the sys_prefix config
jupyter labextension disable --level=user nbgrader/formgrader && \
jupyter labextension enable --level=user nbgrader/formgrader
jupyter labextension disable --level=user nbgrader/create-assignment && \
jupyter labextension enable --level=user nbgrader/create-assignment